---
- name: Celestia-app | Init notify list
  ansible.builtin.set_fact:
    service_list: []

- name: Celestia-app | Set vars (bridge)
  when: chain_celestia_bridge is defined and chain_celestia_bridge | bool
  ansible.builtin.set_fact:
    service_bridge: Restart bridge-celestia-app-{{ chain_celestia_chain_id }}

- name: Celestia-app | Append bridge to notify list
  when: chain_celestia_bridge is defined and chain_celestia_bridge | bool
  ansible.builtin.set_fact:
    service_list: "{{ service_list + [service_bridge] }}"

- name: Celestia-app | Set vars (validator)
  when: chain_celestia_validator is defined and chain_celestia_validator | bool
  ansible.builtin.set_fact:
    service_validator: Restart appd-{{ chain_celestia_chain_id }}

- name: Celestia-app | Append validator to notify list
  when: chain_celestia_validator is defined and chain_celestia_validator | bool
  ansible.builtin.set_fact:
    service_list: "{{ service_list + [service_validator] }}"

- name: Celestia-app | Ensure celestia-appd repository is present
  ansible.builtin.git:
    repo: https://github.com/celestiaorg/celestia-app.git
    dest: "/home/{{ chain_celestia_user }}/celestia-app"
    version: "tags/{{ chain_celestia_appd_version }}"
  become: true
  become_user: "{{ chain_celestia_user }}"
  register: repo_cloned

- name: Celestia-app | Build and install
  when: repo_cloned.changed # noqa: no-handler
  ansible.builtin.shell:
    chdir: /home/{{ chain_celestia_user }}/celestia-app
    cmd: |
      source ~/.bash_profile
      nice -n 19 make install
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ chain_celestia_user }}"
  changed_when: true
  notify: "{{ item }}"
  loop: "{{ service_list }}"
