---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - aria2
      - build-essential
      - git
      - make
      - lz4
      - gcc
    state: present

- name: Create user
  ansible.builtin.user:
    name: "{{ chain_celestia_user }}"
    group: users
    system: true
    create_home: true
    state: present

- name: Add user to systemd-journal group
  ansible.builtin.user:
    name: "{{ chain_celestia_user }}"
    groups: systemd-journal
    append: true

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    mode: "0700"
    owner: "{{ chain_celestia_user }}"
    group: users
  loop:
    - "/home/{{ chain_celestia_user }}/go/bin"

- name: Configure celestia shell
  ansible.builtin.include_role:
    name: binarybuilders.servers.configure_hosts
    tasks_from: shell.yml
  vars:
    configure_hosts_users_username: "{{ chain_celestia_user }}"

- name: Install Go
  ansible.builtin.include_role:
    name: install_go

- name: Celestia-appd
  ansible.builtin.include_tasks: celestia-app.yml

- name: Bridge | Celestia-app
  ansible.builtin.include_tasks: bridge-celestia-app.yml
  when: chain_celestia_bridge is defined and chain_celestia_bridge | bool

- name: Bridge | Celestia-node
  ansible.builtin.include_tasks: celestia-node.yml
  when: chain_celestia_bridge is defined and chain_celestia_bridge | bool

- name: Bridge | Celestia-da-otel-collector
  ansible.builtin.include_tasks: celestia-da-otel-collector.yml
  when: chain_celestia_bridge is defined and chain_celestia_bridge | bool

- name: Bridge | Validator-observability
  when: chain_celestia_bridge is defined and chain_celestia_bridge | bool
  ansible.builtin.include_role:
    name: binarybuilders.validators.observability
  vars:
    observability_unique_id: bridge
    observability_alerts: "{{ chain_celestia_alerts }}"
    observability_chain_id: "{{ chain_celestia_chain_id }}"
    observability_prometheus_sdk_prometheus_port: "{{ chain_celestia_bridge_app_prometheus_port }}"

- name: Validator | Celestia-app
  ansible.builtin.include_tasks: validator-celestia-app.yml
  when: chain_celestia_validator is defined and chain_celestia_validator | bool

- name: Validator | Cosmos-validator-watcher
  ansible.builtin.include_tasks: cosmos-validator-watcher.yml
  when: chain_celestia_validator is defined and chain_celestia_validator | bool

- name: Validator | Validator-observability
  when: chain_celestia_validator is defined and chain_celestia_validator | bool
  ansible.builtin.include_role:
    name: binarybuilders.validators.observability
  vars:
    observability_unique_id: validator
    observability_alerts: "{{ chain_celestia_alerts }}"
    observability_chain_id: "{{ chain_celestia_chain_id }}"
    observability_prometheus_sdk_prometheus_port: "{{ chain_celestia_validator_app_prometheus_port }}"
    observability_prometheus_watcher_prometheus_port: "{{ chain_celestia_validator_watcher_prometheus_port }}"

- name: Deploy justfile
  ansible.builtin.template:
    src: justfile.j2
    dest: /home/{{ chain_celestia_user }}/justfile
    owner: "{{ chain_celestia_user }}"
    group: users
    mode: "0644"
