---
- name: Restart celestia-bridge-{{ chain_celestia_chain_id }}
  ansible.builtin.systemd_service:
    name: celestia-bridge-{{ chain_celestia_chain_id }}
    state: restarted

- name: Restart appd-{{ chain_celestia_chain_id }}
  ansible.builtin.systemd_service:
    name: appd-{{ chain_celestia_chain_id }}
    state: restarted

- name: Restart celestia-bootstrapper-{{ chain_celestia_chain_id }}
  ansible.builtin.systemd_service:
    name: celestia-bootstrapper-{{ chain_celestia_chain_id }}
    state: restarted

- name: Restart celestia-da-otel-collector-{{ chain_celestia_chain_id }}
  ansible.builtin.systemd_service:
    name: celestia-da-otel-collector-{{ chain_celestia_chain_id }}
    state: restarted

- name: Restart celestia-bootstrapper-otel-collector-{{ chain_celestia_chain_id }}
  ansible.builtin.systemd_service:
    name: celestia-da-otel-collector-{{ chain_celestia_chain_id }}
    state: restarted

- name: Restart tmkms-{{ chain_celestia_chain_id }}
  ansible.builtin.systemd_service:
    name: tmkms-{{ chain_celestia_chain_id }}
    state: restarted

- name: Restart cosmos-validator-watcher-{{ chain_celestia_chain_id }}
  ansible.builtin.systemd_service:
    name: cosmos-validator-watcher-{{ chain_celestia_chain_id }}
    state: restarted

- name: Restart alloy
  ansible.builtin.systemd_service:
    name: alloy
    daemon_reload: true
    state: restarted

- name: Restart vmalert
  ansible.builtin.systemd_service:
    name: vmalert
    daemon_reload: true
    state: restarted
  delegate_to: observability

- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    daemon_reload: true
    state: restarted
