---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - aria2
      - build-essential
      - git
      - make
      - lz4
      - gcc
    state: present

- name: Add user to systemd-journal group
  ansible.builtin.user:
    name: "{{ chain_xion_user }}"
    groups: systemd-journal
    append: true

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    mode: "0700"
    owner: "{{ chain_xion_user }}"
    group: users
  loop:
    - "/home/{{ chain_xion_user }}/go/bin"

- name: Install Go
  ansible.builtin.include_role:
    name: install_go

- name: Xiond | Binary
  ansible.builtin.include_tasks: xiond-binary.yml

- name: Xiond | configuration
  ansible.builtin.include_tasks: xiond-configuration.yml

- name: Cosmos-validator-watcher
  ansible.builtin.include_tasks: cosmos-validator-watcher.yml
  tags:
    - cosmos-validator-watcher

- name: Validator-observability
  ansible.builtin.include_role:
    name: binarybuilders.validators.observability
  vars:
    observability_alerts: "{{ chain_xion_alerts }}"
    observability_chain_id: "{{ chain_xion_chain_id }}"
    observability_prometheus_sdk_prometheus_port: "{{ chain_xion_xiond_prometheus_port }}"
    observability_prometheus_watcher_prometheus_port: "{{ chain_xion_watcher_prometheus_port }}"

- name: Deploy justfile
  ansible.builtin.template:
    src: justfile.j2
    dest: /home/{{ chain_xion_user }}/justfile
    owner: "{{ chain_xion_user }}"
    group: users
    mode: "0644"

- name: Backup
  ansible.builtin.include_role:
    name: binarybuilders.validators.global
    tasks_from: backup.yml
  vars:
    global_user: "{{ chain_xion_user }}"
    global_home_dir: "/home/{{ chain_xion_user }}"

- name: Backup directories
  ansible.builtin.copy:
    dest: /home/{{ chain_xion_user }}/scripts/backup_directories.conf
    content: |
      validator:/home/{{ chain_xion_user }}/.xiond/config:/home/{{ chain_xion_user }}/backups
    mode: "0644"
  become: true
  become_user: "{{ chain_xion_user }}"
