---
- name: Xiond | Check if cosmovisor wanted version is installed
  ansible.builtin.shell: |
    source /home/{{ install_go_user }}/.bash_profile
    cosmovisor version
  args:
    executable: /bin/bash
  register: check_cosmovisor
  failed_when: false
  changed_when: false

- name: Xiond | Install cosmovisor {{ chain_xion_cosmovisor_version }}
  when: chain_xion_cosmovisor_version not in check_cosmovisor.stderr
  ansible.builtin.shell:
    cmd: |
      source ~/.bash_profile
      nice -n 19 go install cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@{{ chain_xion_cosmovisor_version }}
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ chain_xion_user }}"
  changed_when: true

- name: Xiond | Check if cosmovisor is already initiated
  ansible.builtin.stat:
    path: /home/{{ chain_xion_user }}/.xiond/cosmovisor/config.toml
  register: cosmovisor_init

- name: Xiond | .bash_profile
  ansible.builtin.blockinfile:
    path: /home/{{ chain_xion_user }}/.bash_profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Cosmovisor"
    block: |
      export DAEMON_NAME=xiond
      export DAEMON_HOME=$HOME/.xiond
      export DAEMON_ALLOW_DOWNLOAD_BINARIES=false
      export DAEMON_LOG_BUFFER_SIZE=512
      export DAEMON_RESTART_AFTER_UPGRADE=true
      export UNSAFE_SKIP_BACKUP=true

- name: Fish config
  ansible.builtin.copy:
    dest: ~/.config/fish/conf.d/xion.fish
    content: |
      set -x DAEMON_NAME xiond
      set -x DAEMON_HOME $HOME/.xiond
      set -x DAEMON_ALLOW_DOWNLOAD_BINARIES false
      set -x DAEMON_LOG_BUFFER_SIZE 512
      set -x DAEMON_RESTART_AFTER_UPGRADE true
      set -x UNSAFE_SKIP_BACKUP true
    mode: "644"
  become: true
  become_user: "{{ chain_xion_user }}"

- name: Xiond | Ensure Xiond repository is present
  ansible.builtin.git:
    repo: https://github.com/burnt-labs/xion.git
    dest: "/home/{{ chain_xion_user }}/xiond"
    version: "tags/{{ chain_xion_xiond_version }}"
  become: true
  become_user: "{{ chain_xion_user }}"
  register: repo_cloned

- name: Xiond | Build and install
  when: repo_cloned.changed # noqa: no-handler
  ansible.builtin.shell:
    chdir: /home/{{ chain_xion_user }}/xiond
    cmd: |
      source ~/.bash_profile
      nice -n 19 make install
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ chain_xion_user }}"
  changed_when: true
  notify: Restart xiond-{{ chain_xion_network }}

- name: Xiond | Initialize Cosmovisor
  when: not cosmovisor_init.stat.exists # noqa: no-handler
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      source ~/.bash_profile
      cosmovisor init $HOME/go/bin/xiond
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ chain_xion_user }}"
  changed_when: true

- name: Xiond | Create cosmovisor update directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    mode: "0755"
    owner: "{{ chain_xion_user }}"
    group: users
  become: true
  become_user: "{{ chain_xion_user }}"
  loop:
    - /home/{{ chain_xion_user }}/.xiond/cosmovisor/upgrades/{{ chain_xion_xiond_upgrade_name }}
    - /home/{{ chain_xion_user }}/.xiond/cosmovisor/upgrades/{{ chain_xion_xiond_upgrade_name }}/bin

- name: Xiond | Copy binary to cosmovisor update directory
  ansible.builtin.copy:
    src: /home/{{ chain_xion_user }}/go/bin/xiond
    dest: /home/{{ chain_xion_user }}/.xiond/cosmovisor/upgrades/{{ chain_xion_xiond_upgrade_name }}/bin/xiond
    mode: "755"
    remote_src: true
  become: true
  become_user: "{{ chain_xion_user }}"

- name: Xiond | Create systemd service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/xiond-{{ chain_xion_network }}.service
    content: |
      [Unit]
      Description=xiond-{{ chain_xion_network }} (Validator)
      After=network.target

      [Service]
      Type=simple
      ExecStart=/home/{{ chain_xion_user }}/go/bin/cosmovisor run start
      User={{ chain_xion_user }}
      Group=users
      Restart=always
      RestartSec=3
      TimeoutStartSec=900
      LimitNOFILE=1400000
      Environment="DAEMON_NAME=xiond"
      Environment="DAEMON_HOME=/home/{{ chain_xion_user }}/.xiond"
      Environment="DAEMON_LOG_BUFFER_SIZE=512"
      Environment="DAEMON_ALLOW_DOWNLOAD_BINARIES=false"
      Environment="DAEMON_RESTART_AFTER_UPGRADE=true"
      Environment="UNSAFE_SKIP_BACKUP=true"

      [Install]
      WantedBy=multi-user.target
    mode: "0644"
  notify: Restart xiond-{{ chain_xion_network }}

- name: Xiond | Enable systemd service
  ansible.builtin.systemd:
    name: xiond-{{ chain_xion_network }}
    enabled: true
    state: started
    daemon_reload: true

- name: Xiond | Add sudoers file
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ chain_xion_user }}-xiond-{{ chain_xion_network }}"
    content: |
      {{ chain_xion_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl start xiond-{{ chain_xion_network }}.service
      {{ chain_xion_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop xiond-{{ chain_xion_network }}.service
      {{ chain_xion_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart xiond-{{ chain_xion_network }}.service
      {{ chain_xion_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl status xiond-{{ chain_xion_network }}.service
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
