[prometheus]
host = '0.0.0.0'
port = 29090

[chain]
watch_list = [
  'cosmos',
  'osmosis',
  'noble',
  'neutron',
  'stride',
  'xion',
]
refresh = '10m'
endpoint = 'https://polkachu.com/api/v2/chain_upgrades'