---
- name: Backup | Create directories
  tags: [backup]
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ global_user }}"
    group: users
  become: true
  become_user: "{{ global_user }}"
  loop:
    - "{{ global_home_dir }}/scripts"

- name: Backup | Copy script
  tags: [backup]
  ansible.builtin.copy:
    src: backup.sh
    dest: "{{ global_home_dir }}/scripts/backup.sh"
    mode: "755"
  become: true
  become_user: "{{ global_user }}"

- name: Backup | Crontab
  tags: [backup]
  ansible.builtin.cron:
    name: backup - 8h
    minute: "2"
    hour: "8"
    job: "{{ global_home_dir }}/scripts/backup.sh"
  become: true
  become_user: "{{ global_user }}"
