---
- name: Cosmos-validator-watcher | Quadlet container file
  containers.podman.podman_container:
    name: cosmos-validator-watcher-{{ global_chain_id }}
    image: "{{ global_cosmos_validator_watcher_image }}"
    state: quadlet
    command: "{{ global_watcher_quadlet_command }}"
    network: host
    label:
      app: "appd-{{ global_chain_id }}"
    quadlet_options:
      - |

        [Unit]
        Description=cosmos-validator-watcher for {{ global_chain_id }}
        After=network-online.target
        Wants=network-online.target

        [Service]
        Restart=always
        RestartSec=3
        TimeoutStartSec=900

        [Install]
        WantedBy=default.target
  notify: Restart cosmos-validator-watcher-{{ global_chain_id }}

- name: Cosmos-validator-watcher | Add sudoers file
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ global_user }}-cosmos-validator-watcher-{{ global_network }}"
    content: |
      {{ global_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl start cosmos-validator-watcher-{{ global_network }}.service
      {{ global_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop cosmos-validator-watcher-{{ global_network }}.service
      {{ global_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart cosmos-validator-watcher-{{ global_network }}.service
      {{ global_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl status cosmos-validator-watcher-{{ global_network }}.service
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s

- name: Cosmos-validator-watcher | Enable systemd service
  ansible.builtin.systemd:
    name: cosmos-validator-watcher-{{ global_chain_id }}
    enabled: true
    state: started
    daemon_reload: true
