---
- name: Binary | Check if cosmovisor wanted version is installed
  ansible.builtin.shell: |
    source /home/{{ install_go_user }}/.bash_profile
    cosmovisor version
  args:
    executable: /bin/bash
  register: check_cosmovisor
  failed_when: false
  changed_when: false

- name: Binary | Install cosmovisor {{ chain_osmosis_cosmovisor_version }}
  when: chain_osmosis_cosmovisor_version not in check_cosmovisor.stderr
  ansible.builtin.shell:
    cmd: |
      source ~/.bash_profile
      go install cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@{{ chain_osmosis_cosmovisor_version }}
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ chain_osmosis_user }}"
  changed_when: true

- name: Binary | Check if cosmovisor is already initiated
  ansible.builtin.stat:
    path: "{{ chain_osmosis_home_dir }}/cosmovisor/config.toml"
  register: cosmovisor_init

- name: Binary | .bash_profile
  ansible.builtin.blockinfile:
    path: /home/{{ chain_osmosis_user }}/.bash_profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Cosmovisor"
    block: |
      export DAEMON_NAME={{ chain_osmosis_binary_name }}
      export DAEMON_HOME={{ chain_osmosis_home_dir }}
      export DAEMON_ALLOW_DOWNLOAD_BINARIES=false
      export DAEMON_LOG_BUFFER_SIZE=512
      export DAEMON_RESTART_AFTER_UPGRADE=true
      export UNSAFE_SKIP_BACKUP=true

- name: Fish config
  ansible.builtin.copy:
    dest: ~/.config/fish/conf.d/{{ chain_osmosis_binary_name }}.fish
    content: |
      set -x DAEMON_NAME {{ chain_osmosis_binary_name }}
      set -x DAEMON_HOME {{ chain_osmosis_home_dir }}
      set -x DAEMON_ALLOW_DOWNLOAD_BINARIES false
      set -x DAEMON_LOG_BUFFER_SIZE 512
      set -x DAEMON_RESTART_AFTER_UPGRADE true
      set -x UNSAFE_SKIP_BACKUP true
    mode: "644"
  become: true
  become_user: "{{ chain_osmosis_user }}"

- name: Binary | Ensure Binary repository is present
  ansible.builtin.git:
    repo: https://github.com/osmosis-labs/osmosis.git
    dest: "/home/{{ chain_osmosis_user }}/osmosis"
    version: "tags/{{ chain_osmosis_osmosisd_version }}"
  become: true
  become_user: "{{ chain_osmosis_user }}"
  register: repo_cloned

- name: Binary | Build and install
  when: repo_cloned.changed # noqa: no-handler
  ansible.builtin.shell:
    chdir: /home/{{ chain_osmosis_user }}/osmosis
    cmd: |
      source ~/.bash_profile
      make install
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ chain_osmosis_user }}"
  changed_when: true
  notify: Restart {{ chain_osmosis_binary_name }}-{{ chain_osmosis_network }}

- name: Binary | Initialize Cosmovisor
  when: not cosmovisor_init.stat.exists # noqa: no-handler
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      source ~/.bash_profile
      cosmovisor init $HOME/go/bin/{{ chain_osmosis_binary_name }}
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ chain_osmosis_user }}"
  changed_when: true

- name: Binary | Create cosmovisor update directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    mode: "0755"
    owner: "{{ chain_osmosis_user }}"
    group: users
  become: true
  become_user: "{{ chain_osmosis_user }}"
  loop:
    - "{{ chain_osmosis_home_dir }}/cosmovisor/upgrades/{{ chain_osmosis_osmosisd_upgrade_name }}"
    - "{{ chain_osmosis_home_dir }}/cosmovisor/upgrades/{{ chain_osmosis_osmosisd_upgrade_name }}/bin"

- name: Binary | Copy binary to cosmovisor update directory
  ansible.builtin.copy:
    src: /home/{{ chain_osmosis_user }}/go/bin/{{ chain_osmosis_binary_name }}
    dest: "{{ chain_osmosis_home_dir }}/cosmovisor/upgrades/{{ chain_osmosis_osmosisd_upgrade_name }}/bin/{{ chain_osmosis_binary_name }}"
    mode: "755"
    remote_src: true
  become: true
  become_user: "{{ chain_osmosis_user }}"

- name: Binary | Create systemd service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/{{ chain_osmosis_binary_name }}-{{ chain_osmosis_network }}.service
    content: |
      [Unit]
      Description={{ chain_osmosis_binary_name }}-{{ chain_osmosis_network }} (Validator)
      After=network.target

      [Service]
      Type=simple
      ExecStart=/home/{{ chain_osmosis_user }}/go/bin/cosmovisor run start
      User={{ chain_osmosis_user }}
      Group=users
      Restart=always
      RestartSec=3
      TimeoutStartSec=900
      LimitNOFILE=1400000
      Environment="DAEMON_NAME={{ chain_osmosis_binary_name }}"
      Environment="DAEMON_HOME={{ chain_osmosis_home_dir }}"
      Environment="DAEMON_LOG_BUFFER_SIZE=512"
      Environment="DAEMON_ALLOW_DOWNLOAD_BINARIES=false"
      Environment="DAEMON_RESTART_AFTER_UPGRADE=true"
      Environment="UNSAFE_SKIP_BACKUP=true"

      [Install]
      WantedBy=multi-user.target
    mode: "0644"
  notify: Restart {{ chain_osmosis_binary_name }}-{{ chain_osmosis_network }}

- name: Binary | Enable systemd service
  ansible.builtin.systemd:
    name: "{{ chain_osmosis_binary_name }}-{{ chain_osmosis_network }}"
    enabled: true
    state: started
    daemon_reload: true

- name: Binary | Add sudoers file
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ chain_osmosis_user }}-{{ chain_osmosis_binary_name }}-{{ chain_osmosis_network }}"
    content: |
      {{ chain_osmosis_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl start {{ chain_osmosis_binary_name }}-{{ chain_osmosis_network }}.service
      {{ chain_osmosis_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop {{ chain_osmosis_binary_name }}-{{ chain_osmosis_network }}.service
      {{ chain_osmosis_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart {{ chain_osmosis_binary_name }}-{{ chain_osmosis_network }}.service
      {{ chain_osmosis_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl status {{ chain_osmosis_binary_name }}-{{ chain_osmosis_network }}.service
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
